name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8']
        django: ['3.0', '3.1']
        wagtail: ['2.14', '2.15']
        include:
          - python: '3.9'
            django: '3.2'
            wagtail: '2.16'
          - python: '3.10'
            django: '4.0'
            wagtail: '3.0'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: python -m pip install tox
      - name: Test
        run: tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-sqlite